name: Deploy Gatsby App

on:
  push:
    branches: [main]
#     paths:
#       - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: npm install

    - name: Build Gatsby site
      run: npm run build

    - name: Deploy to DigitalOcean
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOY_HOST: discourse.guildofentrepreneurs.com
        DEPLOY_DIR: /var/www/sites/guild-site/htdocs/
      run: |
        # Setup SSH agent
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add ~/.ssh/id_rsa
        # Sync build directory to remote server
        rsync -avz --delete public/ $SSH_USERNAME@$DEPLOY_HOST:$DEPLOY_DIR

    
#     - name: Deploy to DigitalOcean            
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.DROPLET_HOST }}
#         username: ${{ secrets.DROPLET_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           sudo mkdir -p /var/www/sites/guild-site/htdocs
#           sudo cp -r src/public/* /var/www/sites/guild-site/htdocs/
#           sudo chown -R www-data:www-data /var/www/sites/guild-site/htdocs
#           sudo chmod -R 755 /var/www/sites/guild-site/htdocs
#           #sudo service nginx restart
