name: Deploy Gatsby App

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm install

    - name: Build Gatsby site
      run: npm run build

    - name: Deploy to DigitalOcean
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOY_HOST: discourse.guildofentrepreneurs.com
        DEPLOY_DIR: /var/www/sites/guild-site/htdocs/
      run: |
        # Start the SSH agent
        #echo "starting agent"
        eval "$(ssh-agent -s)"
        # Add the SSH private key to the agent
        #echo "adding ssh key to agent"
        ssh-add <(echo "$SSH_PRIVATE_KEY")
        # Add the host to the list of known hosts
        #echo "adding host to the list of known hosts"
        mkdir -p ~/.ssh
        # chmod 600 ~/.ssh
        ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        # Sync build directory to remote server
        echo "syncing to: $SSH_USERNAME@$DEPLOY_HOST:$DEPLOY_DIR"
        rsync -avz --delete public/ $SSH_USERNAME@$DEPLOY_HOST:$DEPLOY_DIR

    
#     - name: Deploy to DigitalOcean            
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.DROPLET_HOST }}
#         username: ${{ secrets.DROPLET_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           sudo mkdir -p /var/www/sites/guild-site/htdocs
#           sudo cp -r src/public/* /var/www/sites/guild-site/htdocs/
#           sudo chown -R www-data:www-data /var/www/sites/guild-site/htdocs
#           sudo chmod -R 755 /var/www/sites/guild-site/htdocs
#           #sudo service nginx restart
